//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DNxMediaPlayer
{
    public class Functie
    {
        public virtual void Next()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Previous()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Pause()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Play()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Shuffle()
        {
            throw new System.NotImplementedException();
        }

        public virtual void Replay()
        {
            throw new System.NotImplementedException();
        }

    }


}
